Improve the default Git config

diff --git a/app/git/gitconfig-global b/app/git/gitconfig-global
--- a/app/git/gitconfig-global
+++ b/app/git/gitconfig-global
@@ -29,46 +29,168 @@
 
 [alias]  # {{{1
     a = add
+
+    # Add all unstaged changes.
     aa = add --all
+
     br = branch
-    # Assume we want interactive commit by default.
+
+    # Assume we want an interactive commit by default.
     c = commit
-    # Commit all changes.
+
+    # Commit all unstaged changes, interactively.
     ca = !git add --all && git commit
+
     # Using 'i' for interactive here.
     ci = commit
-    # Don't mask 'clean'.
+
+    # Clean up the repo. Don't mask `clean` with an alias!
     cleanup = !git remote prune origin \
         && git gc \
         && git clean -dfx \
         && git stash clear
+
+    # Commit with a message, non-interactively.
     cm = commit -m
+
+    # List contributors, ordered by the number of commits.
+    contrib = shortlog --email --numbered --summary
+
     co = checkout
+
+    d = diff -- . \
+        ':!*package-lock.json' \
+        ':!*yarn.lock'
+
+    dc = diff --cached -- . \
+        ':!*package-lock.json' \
+        ':!*yarn.lock'
+
+    f = fetch
+
     # Find commits by source code.
     find = "!f() { \
         git log --date=short --decorate --pretty=custom -S\"$1\"; \
     }; f"
+
     # Find commits by commit message.
     find-msg = "!f() { \
         git log --date=short --decorate --pretty=custom --grep=\"$1\"; \
     }; f"
+
+    # EXPERIMENTAL. Credit an author on the latest commit.
+    credit = "!f() { \
+        if [ -n \"$1\" ] && [ -n \"$2\" ]; then \
+            git commit --amend --author \"$1 <$2>\" --no-edit --reuse-message=HEAD; \
+        fi \
+    }; f"
+
+    # EXPERIMENTAL. Credit a co-author on the latest commit.
+    # See also:
+    # - https://help.github.com/en/articles/
+    #     creating-a-commit-with-multiple-authors
+    # - https://help.github.com/en/articles/
+    #     creating-a-commit-on-behalf-of-an-organization
+    credit-co-author = "!f() { \
+        if [ -n \"$1\" ] && [ -n \"$2\" ]; then \
+            GIT_EDITOR=\"git interpret-trailers --in-place --trailer='Co-authored-by: $1 <$2>'\" git commit --amend; \
+        fi \
+    }; f"
+
     cp = cherry-pick
-    glog = log --graph
-    grog = log --graph --abbrev-commit --decorate --all
+
+    # Show custom text-based graphical log of the commit history.
+    # Currently there's not an easy way to reverse graph mode natively.
+    # https://zwischenzugs.com/2016/06/04/power-git-log-graphing/
+    glog = log \
+        --abbrev-commit \
+        --all \
+        --decorate \
+        --graph \
+        --oneline \
+        --simplify-by-decoration
+    # > glog2 = log \
+    # >     --abbrev-commit \
+    # >     --all \
+    # >     --graph \
+    # >     --pretty=custom
+
+    # Show custom log of the commit history.
+    l = log --pretty=custom
+
+    # Show the last commit.
     last = log -1 HEAD
-    lol = log --graph --decorate --pretty=oneline --abbrev-commit
-    lola = log --graph --decorate --pretty=oneline --abbrev-commit --all
+
+    # List remote branches. Defaults to "origin".
+    lrb = "!f() { \
+        remote=\"${1:-origin}\"; \
+        git ls-remote --heads \"$remote\"; \
+    }; f"
+
+    # EXPERIMENTAL. Merge GitHub pull request on top of the current branch or,
+    # if a branch name is specified, on top of the specified branch.
+    mpr = "!f() { \
+        current_branch=\"$(git symbolic-ref --short HEAD)\"; \
+        branch=\"${2:-$current_branch}\"; \
+        if [ $(printf \"%s\" \"$1\" | grep '^[0-9]\\+$' > /dev/null; printf $?) -eq 0 ]; then \
+            git fetch origin refs/pull/$1/head:pr/$1 && \
+            git checkout -B \"$branch\" && \
+            git rebase \"$branch\" pr/$1 && \
+            git checkout -B \"$branch\" && \
+            git merge pr/$1 && \
+            git branch --delete --force pr/$1 && \
+            git commit --amend --message=\"$(git log -1 --pretty=%B)\n\nClose: #$1\"; \
+        fi \
+    }; f"
+
     p = push
+
     pr = !sh -c 'git fetch origin pull/$1/head:pr$1' -
+
     r = rebase
+
+    # Remove the tag with the specified tag name if exists and tag the latest
+    # commit with that name.
+    retag = "!f() { \
+        git tag --delete \"$1\" &> /dev/null; \
+        git tag \"$1\"; \
+    }; f"
+
     s = status
+
     shorty = status --short --branch
+
     st = status -sb
+
     trash = checkout --
+
+    # Update the content of the last commit by including all staged changes.
+    # Note that the term "update" is used here loosely. Git doesn't actually
+    # update the last commit, but instead, creates a new commit based on the
+    # last commit and replaces it.
+    u = commit --amend --no-edit
+
+    # Update the content of the last commit by including all local changes.
+    ua = !git add --all && git commit --amend --no-edit
+
+    # Update the content of the last commit, including all staged changes, and
+    # allow the user to change the commit message.
+    um = commit --amend
+
+    # Undo commits. By default, only reverts the last commit.
+    undo = "!f() { \
+        num=\"${1:-1}\"; \
+        git reset --soft \"HEAD~$num\"; \
+    }; f"
+
     unstage = reset HEAD --
+
     up = !sh -c 'git pull --rebase --prune && git log --pretty HEAD@{1}..'
-    # Start web-based visualizer.
+
+    # Start web-based visualizer. This is super cool, give it a try.
+    # If you hit a Ruby error, run `gem install webrick` to resolve.
     w = instaweb --httpd=webrick
+
     who = shortlog -n -s --no-merges
 
 [color]  # {{{1
@@ -131,10 +253,10 @@
 
 [filter "lfs"]  # {{{1
     # Large file storage (LFS).
-    required = true
     clean = git-lfs clean -- %f
-    smudge = git-lfs smudge -- %f
     process = git-lfs filter-process
+    required = true
+    smudge = git-lfs smudge -- %f
 
 [fsck]  # {{{1
     zeroPaddedFilemode = warn
